theme: type-theme
title: Blog.JujinKim.com
gravatar: b29ffe51445057ea65f5a687e8a2ac63
description: Jujin Kim's weblog. Welcome to OhRockInJourneyStudio
header_text: Blog.JujinKim.com
footer_text: Copyright 2018, Jujin Kim from OhRockInJourney
rss: true
email_address: jk012345@gmail.com
linkedin: https://www.linkedin.com/in/jujinkim
google_analytics: UA-54002449-5
katex: false
disqus_shortname: blog-jujinkim-com
---
layout: default
comments: true
# other options
---
